### PR TITLE
Added Chinese translation and automatic theme color switcher.

### PR DESCRIPTION
**Pull request by listill**
Since I discovered the extension, it has saved me a lot of time securing email addresses.

To make this extension better, I did the following two things.

1. Added an "Auto" theme pattern to follow the system's preferences.
2. added Chinese support, I believe this can help more Chinese users to use the extension better.

Finally, thank you for the open source.

### CODE REVIEW

**Comment by Curetix** [comment]
Thanks a lot for your contribution, I just made some small adjustments. If you have any other suggestions, feel free to let me know 🙂

**Comment by listill** [comment]
As a small suggestion, I've adjusted the `LANGUAGE_ENGLISH` field in Chinese based on your change, which is only a one character change.

Do I need to start a new Pull Request, or can you check my commit and you can do the change?

~~`LANGUAGE_ENGLISH: "🇬🇧 英文 (English)",`~~
`LANGUAGE_ENGLISH: "🇬🇧 英语 (English)",`

**Comment by Curetix** [comment]
> As a small suggestion, I've adjusted the `LANGUAGE_ENGLISH` field in Chinese based on your change, which is only a one character change.
> 
> Do I need to start a new Pull Request, or can you check my commit and you can do the change?
> 
> ~`LANGUAGE_ENGLISH: "🇬🇧 英文 (English)",`~ `LANGUAGE_ENGLISH: "🇬🇧 英语 (English)",`

No problem, I updated it.

**Comment by listill** [comment]
Great, I don't have any other more suggestions for now.

**Pull request merged**
